<?xml version="1.0" encoding="UTF-8"?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.shellmind</groupId>
  <artifactId>shellmind-server</artifactId>
  <version>1.0</version>
  <packaging>pom</packaging>
  <repositories>
    <repository>
      <id>nexus-aliyun</id>
      <name>nexus-aliyun</name>
      <url>https://maven.aliyun.com/repository/public</url>
      <releases/>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
  </repositories>
  <properties>
    <java.version>17</java.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <google.adk.version>1.10.1</google.adk.version>
    <archunit.version>1.3.0</archunit.version>
  </properties>
  <developers>
    <developer>
      <name>xiaofuge</name>
      <email>184172133@qq.com</email>
      <organization>fuzhengwei</organization>
      <organizationUrl>https://github.com/fuzhengwei</organizationUrl>
    </developer>
  </developers>
  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0</url>
    </license>
  </licenses>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>4.0.2</version>
    <!-- Optional upgrade to AI 2.0.0-M2 plus skills spring-ai-agent-utils -->
    <!--<version>4.1.0-M1</version>-->
  </parent>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.tngtech.archunit</groupId>
        <artifactId>archunit-junit5</artifactId>
        <version>${archunit.version}</version>
      </dependency>
      <dependency>
        <groupId>org.mybatis.spring.boot</groupId>
        <artifactId>mybatis-spring-boot-starter</artifactId>
        <version>4.1.0</version>
      </dependency>
      <dependency>
        <groupId>org.springframework.retry</groupId>
        <artifactId>spring-retry</artifactId>
        <version>2.0.11</version>
      </dependency>
      <dependency>
        <groupId>com.openai</groupId>
        <artifactId>openai-java-client-okhttp</artifactId>
        <version>4.49.0</version>
      </dependency>
      <!-- # Multi-datasource routing configuration
                 # mysql 5.x driver-class-name: com.mysql.jdbc.Driver    mysql-connector-java 5.1.34
                 # mysql 8.x driver-class-name: com.mysql.cj.jdbc.Driver mysql-connector-java 8.0.22-->
      <dependency>
        <groupId>mysql</groupId>
        <artifactId>mysql-connector-java</artifactId>
        <version>8.0.28</version>
      </dependency>
      <dependency>
        <groupId>com.alibaba</groupId>
        <artifactId>fastjson</artifactId>
        <version>2.0.28</version>
      </dependency>
      <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-lang3</artifactId>
        <version>3.9</version>
      </dependency>
      <dependency>
        <groupId>com.google.guava</groupId>
        <artifactId>guava</artifactId>
        <version>32.1.3-jre</version>
      </dependency>
      <dependency>
        <groupId>commons-codec</groupId>
        <artifactId>commons-codec</artifactId>
        <version>1.15</version>
      </dependency>
      <dependency>
        <groupId>com.google.adk</groupId>
        <artifactId>google-adk</artifactId>
        <version>${google.adk.version}</version>
      </dependency>
      <dependency>
        <groupId>com.google.adk</groupId>
        <artifactId>google-adk-dev</artifactId>
        <version>${google.adk.version}</version>
      </dependency>
      <dependency>
        <groupId>com.google.adk</groupId>
        <artifactId>google-adk-spring-ai</artifactId>
        <version>${google.adk.version}</version>
      </dependency>
      <dependency>
        <groupId>com.google.adk.samples</groupId>
        <artifactId>google-adk-sample-helloworld</artifactId>
        <version>${google.adk.version}</version>
      </dependency>
      <dependency>
        <groupId>com.google.adk</groupId>
        <artifactId>google-adk-langchain4j</artifactId>
        <version>${google.adk.version}</version>
      </dependency>
      <!--            <dependency>-->
      <!--                <groupId>dev.langchain4j</groupId>-->
      <!--                <artifactId>langchain4j-core</artifactId>-->
      <!--                <version>1.4.0</version>-->
      <!--            </dependency>-->
      <!--            <dependency>-->
      <!--                <groupId>dev.langchain4j</groupId>-->
      <!--                <artifactId>langchain4j-open-ai</artifactId>-->
      <!--                <version>1.4.0</version>-->
      <!--            </dependency>-->
      <!-- spring ai 1.1.0 https://central.sonatype.com/artifact/org.springframework.ai/spring-ai-bom -->
      <dependency>
        <groupId>org.springframework.ai</groupId>
        <artifactId>spring-ai-bom</artifactId>
        <version>2.0.1</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <!-- Optional upgrade configuration -->
      <!--<dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-openai</artifactId>
                <version>2.0.0-M2</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-model</artifactId>
                <version>2.0.0-M2</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-mcp</artifactId>
                <version>2.0.0-M2</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-starter-mcp-client-webflux</artifactId>
                <version>2.0.0-M2</version>
            </dependency>-->
      <!-- langchain4j https://mvnrepository.com/artifact/dev.langchain4j/langchain4j-bom -->
      <dependency>
        <groupId>dev.langchain4j</groupId>
        <artifactId>langchain4j-bom</artifactId>
        <version>1.10.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <!-- https://github.com/spring-ai-community/spring-ai-agent-utils -->
      <dependency>
        <groupId>org.springaicommunity</groupId>
        <artifactId>spring-ai-agent-utils</artifactId>
        <version>0.12.0</version>
      </dependency>
      <!-- Design-pattern framework -->
      <!-- Project modules -->
      <dependency>
        <groupId>com.shellmind</groupId>
        <artifactId>shellmind-server-api</artifactId>
        <version>1.0</version>
      </dependency>
      <dependency>
        <groupId>com.shellmind</groupId>
        <artifactId>shellmind-server-domain</artifactId>
        <version>1.0</version>
      </dependency>
      <dependency>
        <groupId>com.shellmind</groupId>
        <artifactId>shellmind-server-infrastructure</artifactId>
        <version>1.0</version>
      </dependency>
      <dependency>
        <groupId>com.shellmind</groupId>
        <artifactId>shellmind-server-case</artifactId>
        <version>1.0</version>
      </dependency>
      <dependency>
        <groupId>com.shellmind</groupId>
        <artifactId>shellmind-server-types</artifactId>
        <version>1.0</version>
      </dependency>
      <dependency>
        <groupId>com.shellmind</groupId>
        <artifactId>shellmind-server-trigger</artifactId>
        <version>1.0</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <build>
    <plugins>
      <!-- Maven archetype -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-archetype-plugin</artifactId>
        <version>3.2.0</version>
        <configuration>
          <outputDirectory>${project.build.directory}/ai-agent-scaffold-lite-archetype</outputDirectory>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.11.0</version>
        <configuration>
          <source>${java.version}</source>
          <target>${java.version}</target>
          <encoding>${project.build.sourceEncoding}</encoding>
          <annotationProcessorPaths>
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
              <version>1.18.38</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <version>2.5</version>
        <configuration>
          <encoding>UTF-8</encoding>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>versions-maven-plugin</artifactId>
        <version>2.7</version>
      </plugin>
    </plugins>
  </build>
  <modules>
    <module>shellmind-server-api</module>
    <module>shellmind-server-app</module>
    <module>shellmind-server-domain</module>
    <module>shellmind-server-trigger</module>
    <module>shellmind-server-infrastructure</module>
    <module>shellmind-server-types</module>
      <module>shellmind-server-case</module>
  </modules>
</project>
